baseURL = "/"
languageCode = "fa-ir"
paginate = 3
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = true

[module]
  [module.hugoVersion]
    extended = true
    min = "0.55.0"

[params]
  google_analytics_id = ""
  twitter_handle = "@motzarte"
  showAuthorOnHomepage = true
  showAuthorOnPosts = true
  showPostsOnHomepage = true
  addDot = true
  addFrame = false
  highlightColor = '#7b16ff'
  baseColor = "#ffffff"
  baseOffsetColor = "#eaeaea"
  headingColor = "#1c1b1d"
  textColor = "#4e5157"
  dotColor = "#7b16ff"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = true
      xhtml = true

[menu]
  [[menu.main]]
    identifier = 'home'
    name = 'خانه'
    url = '/'
    weight = 1
  [[menu.main]]
    name = "تگ‌ها"
    identifier = "tags"
    weight = 300
    url = "/tags/"

